# NumPy

In [ ]:
import numpy as np

## Crear Arreglos de diferentes dimensiones

In [ ]:
value = 10 #rank 0
value_as_array = np.array(value)

value_as_array

array(10)

In [ ]:
value = [21, 83, 42, 35] #rank 1
value_as_array = np.array(value)

value_as_array

array([21, 83, 42, 35])

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]] #rank 2
value_as_array = np.array(value)

value_as_array

array([[21, 83, 42],
       [35, 12, 67]])

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ] #rank 3
value_as_array = np.array(value)

value_as_array

array([[[21, 83, 42],
        [35, 12, 67]],

       [[56, 98, 24],
        [64, 78, 98]]])

## Atributos de los Arreglos

In [ ]:
value = [[21, 83, 42],
         [35, 12, 67]]
value_as_array = np.array(value)

In [ ]:
#Number of axes
value_as_array.ndim

2

In [ ]:
#Length (number of elements) of each of the axes of a Tensor
value_as_array.shape

(2, 3)

In [ ]:
#Type of every element in the Tensor
value_as_array.dtype

dtype('int64')

## Operaciones con Arreglos

In [ ]:
value_1 = [[21, 83],
           [42, 35]]
value_2 = [[95, 78],
           [65, 32]]

array_1 = np.array(value_1)
array_2 = np.array(value_2)

### Suma

In [ ]:
np.add(array_1, array_2)

array([[116, 161],
       [107,  67]])

In [ ]:
array_1 + array_2

array([[116, 161],
       [107,  67]])

### Resta

In [ ]:
np.subtract(array_1, array_2)

array([[-74,   5],
       [-23,   3]])

In [ ]:
array_1 - array_2

array([[-74,   5],
       [-23,   3]])

### Multiplicación de elementos

In [ ]:
np.multiply(array_1, array_2)

array([[1995, 6474],
       [2730, 1120]])

In [ ]:
array_1 * array_2

array([[1995, 6474],
       [2730, 1120]])

### Multiplicación de matrices

In [ ]:
#N,M   M,L   ->  N,L
np.matmul(array_1, array_2)

array([[7390, 4294],
       [6265, 4396]])

In [ ]:
array_1 @ array_2

array([[7390, 4294],
       [6265, 4396]])

## Obtener la transpuesta

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
np.transpose(value_as_array)

array([[[21, 56],
        [35, 64]],

       [[83, 98],
        [12, 78]],

       [[42, 24],
        [67, 98]]])

In [ ]:
value_as_array.T

array([[[21, 56],
        [35, 64]],

       [[83, 98],
        [12, 78]],

       [[42, 24],
        [67, 98]]])

## Obtener la inversa

In [ ]:
value = [[21, 83],
         [35, 12]]
value_as_array = np.array(value, dtype=np.float32)

In [ ]:
value_as_array

array([[21., 83.],
       [35., 12.]], dtype=float32)

In [ ]:
np.linalg.inv(value_as_array)

array([[-0.00452318,  0.03128534],
       [ 0.01319261, -0.00791557]], dtype=float32)

## Obtener la cantidad de elementos

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
np.size(value_as_array)

12

In [ ]:
value_as_array.size

12

## Obtener el mayor elemento

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
np.max(value_as_array, axis=0)

array([[56, 98, 42],
       [64, 78, 98]])

In [ ]:
np.max(value_as_array, axis=1)

array([[35, 83, 67],
       [64, 98, 98]])

In [ ]:
np.max(value_as_array, axis=2)

array([[83, 67],
       [98, 98]])

In [ ]:
np.max(value_as_array, axis=-1) #-1: last_possible_axis

array([[83, 67],
       [98, 98]])

## Obtener el índice del mayor elemento

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
#56>21, 98>83, 42>24
#64>35, 78>12, 98>67
np.argmax(value_as_array, axis=0)

array([[1, 1, 0],
       [1, 1, 1]])

In [ ]:
#35>21, 83>12, 67>42
#64>56, 98>78, 98>24
np.argmax(value_as_array, axis=1)

array([[1, 0, 1],
       [1, 0, 1]])

In [ ]:
#83>42>21, 67>35>12
#98>56>24, 98>78>64
np.argmax(value_as_array, axis=2)

array([[1, 2],
       [1, 2]])

In [ ]:
np.argmax(value_as_array, axis=-1) #-1: last_possible_axis

array([[1, 2],
       [1, 2]])

## Indexación

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

In [ ]:
value_as_array[0]

array([[21, 83, 42],
       [35, 12, 67]])

In [ ]:
value_as_array[1]

array([[56, 98, 24],
       [64, 78, 98]])

In [ ]:
value_as_array[0:1]

array([[[21, 83, 42],
        [35, 12, 67]]])

In [ ]:
value_as_array[1:2]

array([[[56, 98, 24],
        [64, 78, 98]]])

In [ ]:
value_as_array[0, 0]

array([21, 83, 42])

In [ ]:
value_as_array[0, 1]

array([35, 12, 67])

In [ ]:
value_as_array[:, 0]

array([[21, 83, 42],
       [56, 98, 24]])

In [ ]:
value_as_array[:, 1]

array([[35, 12, 67],
       [64, 78, 98]])

In [ ]:
value_as_array[0, 0, 0]

21

In [ ]:
value_as_array[0, 0, 1]

83

In [ ]:
value_as_array[0, 0, 2]

42

In [ ]:
value_as_array[:, :, 0]

array([[21, 35],
       [56, 64]])

In [ ]:
value_as_array[:, :, 1]

array([[83, 12],
       [98, 78]])

In [ ]:
value_as_array[:, :, 2]

array([[42, 67],
       [24, 98]])

## Manipulando *Shapes*

In [ ]:
value = [ [[21, 83, 42],
           [35, 12, 67]],
          [[56, 98, 24],
           [64, 78, 98]] ]
value_as_array = np.array(value)

value_as_array.shape

(2, 2, 3)

In [ ]:
np.reshape(value_as_array, (12,))

array([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98])

In [ ]:
np.reshape(value_as_array, (2, 6))

array([[21, 83, 42, 35, 12, 67],
       [56, 98, 24, 64, 78, 98]])

In [ ]:
np.reshape(value_as_array, (4, 3))

array([[21, 83, 42],
       [35, 12, 67],
       [56, 98, 24],
       [64, 78, 98]])

In [ ]:
np.reshape(value_as_array, (3, 4))

array([[21, 83, 42, 35],
       [12, 67, 56, 98],
       [24, 64, 78, 98]])

In [ ]:
np.reshape(value_as_array, (-1,))

array([21, 83, 42, 35, 12, 67, 56, 98, 24, 64, 78, 98])

In [ ]:
np.reshape(value_as_array, (3, -1))

array([[21, 83, 42, 35],
       [12, 67, 56, 98],
       [24, 64, 78, 98]])

## Convertir Arreglos a Listas

In [ ]:
value = [21, 83, 42, 35]
value_as_array = np.array(value)

In [ ]:
value_as_array.tolist()

[21, 83, 42, 35]

In [ ]:
list(value_as_array)

[21, 83, 42, 35]

# Ejercicio

## NumPy

In [ ]:
import numpy as np

np.random.seed(0)

In [ ]:
x = np.arange(100)/100
y = x + np.random.normal(scale=0.05, size=100)

In [ ]:
#Agregamos 1's en la primera columna al arreglo de x
x = np.array([np.array([1, i]) for i in x])

In [ ]:
y = y.reshape((-1, 1))

Calcular $ z = (x^{T} x)^{-1} x^{T}y $